version: "3"

services: 
  api:
    build:
      args: 
        UID: 1000 
        GID: 1000 
      context: .
      dockerfile: ./api/dockerfile
    container_name: api
    hostname: api
    restart: always
    volumes:
      - ./api:/app
      - ./.env:/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.api-pokemon-secure.entrypoints=websecure"
      - "traefik.http.routers.api-pokemon-secure.rule=Host(`api.${DOMAIN_NAME}`)"
      - "traefik.http.routers.api-pokemon-secure.service=api-pokemon"
      - "traefik.http.services.api-pokemon.loadbalancer.server.port=8000" 

  db:
    image: mariadb:10.3.9
    container_name: db
    hostname: db
    restart: always
    env_file:
      - .env
    volumes:
      - ../db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    env_file:
      - .env
    restart: always
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.phpmyadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-secure.rule=Host(`phpmyadmin.${DOMAIN_NAME}`)"
      - "traefik.http.routers.phpmyadmin-secure.service=phpmyadmin"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80" 

  react:
    build:
      args: 
        UID: 1000 
        GID: 1000
      context: ./app
      dockerfile: dockerfile
    container_name: react
    hostname: react
    restart: always
    volumes:
      - ./app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.react-secure.entrypoints=websecure"
      - "traefik.http.routers.react-secure.rule=Host(`www.${DOMAIN_NAME}`)"
      - "traefik.http.routers.react-secure.service=react"
      - "traefik.http.services.react.loadbalancer.server.port=3000" 

  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik_data/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik_data/acme.json:/acme.json
      - ./traefik_data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=hugo:$$apr1$$aIHLX2gY$$CV7XKjRpwaWxlbJvZrwa90"
