version: "3"

services: 
  api:
    build:
      args: 
          UID: 1000 
          GID: 1000 
      context: .
      dockerfile: ./api/dockerfile
    container_name:  api
    hostname: api
    restart:  always
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
      - ./.env:/app/.env 

  db:
    image: mariadb:10.3.9
    container_name: db
    hostname: db
    restart: always
    env_file:
      - .env
    volumes:
      - /home/hugo/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    env_file:
      - .env
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      # - PMA_USER=${DB_USERNAME}
      # - PMA_PASSWORD=${DB_PASSWORD}

  react:
    build:
      args: 
          UID: 1000 
          GID: 1000
      context: ./app
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app


# volumes:
#   api: 