import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins} from 'next/font/google'
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-poppins',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("light", `${poppins.variable}`)}>
      <body className={cn(
        'min-h-screen font-title antialiased dark:bg-KolectorsRed',
      )}>
        <nav>coucou</nav>{/* This is where the navbar will go */} 
        {children}
      </body>
    </html>
  );
}
